/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateYearArgs } from "./CreateYearArgs";
import { UpdateYearArgs } from "./UpdateYearArgs";
import { DeleteYearArgs } from "./DeleteYearArgs";
import { YearCountArgs } from "./YearCountArgs";
import { YearFindManyArgs } from "./YearFindManyArgs";
import { YearFindUniqueArgs } from "./YearFindUniqueArgs";
import { Year } from "./Year";
import { YearService } from "../year.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Year)
export class YearResolverBase {
  constructor(
    protected readonly service: YearService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "read",
    possession: "any",
  })
  async _yearsMeta(
    @graphql.Args() args: YearCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Year])
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "read",
    possession: "any",
  })
  async years(@graphql.Args() args: YearFindManyArgs): Promise<Year[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Year, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "read",
    possession: "own",
  })
  async year(@graphql.Args() args: YearFindUniqueArgs): Promise<Year | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Year)
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "create",
    possession: "any",
  })
  async createYear(@graphql.Args() args: CreateYearArgs): Promise<Year> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Year)
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "update",
    possession: "any",
  })
  async updateYear(@graphql.Args() args: UpdateYearArgs): Promise<Year | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Year)
  @nestAccessControl.UseRoles({
    resource: "Year",
    action: "delete",
    possession: "any",
  })
  async deleteYear(@graphql.Args() args: DeleteYearArgs): Promise<Year | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
